Removed big-calldata check again due to timing

diff --git a/.github/workflows/ci_l1.yaml b/.github/workflows/ci_l1.yaml
--- a/.github/workflows/ci_l1.yaml
+++ b/.github/workflows/ci_l1.yaml
@@ -212,14 +212,19 @@ jobs:
     # "Integration Test" is a required check, don't change the name
     name: Integration Test
     runs-on: ubuntu-latest
-    needs: [run-assertoor, run-hive]
+    needs: [run-assertoor-tx-check, run-assertoor-blob-check, run-hive]
     # Make sure this job runs even if the previous jobs failed or were skipped  
     if: ${{ always() && needs.run-assertoor.result != 'skipped' && needs.run-hive.result != 'skipped' }}
     steps:
       - name: Check if any job failed
         run: |
-          if [ "${{ needs.run-assertoor.result }}" != "success" ]; then
-            echo "Job Assertoor failed"
+          if [ "${{ needs.run-assertoor-tx-check.result }}" != "success" ]; then
+            echo "Job Assertoor Tx Check failed"
+            exit 1
+          fi
+
+          if [ "${{ needs.run-assertoor-blob-check.result }}" != "success" ]; then
+            echo "Job Assertoor Blob Check failed"
             exit 1
           fi
 
